name: arcadia
description: A Flutter clone of the Gemini UI.
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # For rendering markdown
  gpt_markdown: ^1.1.3
  
  # For state management
  provider: ^6.1.5+1

  # For saving settings
  shared_preferences: ^2.5.3
  
  # For Material You / dynamic color
  dynamic_color: ^1.8.1

  # For the 'About' section in settings
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0

  # For slick animations
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/themes/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
