name: arcadia
description: A Flutter clone of the Gemini UI.
publish_to: 'none'
version: 1.1.1-beta.2+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # renders markdown
  gpt_markdown: ^1.1.3
  # state management
  provider: ^6.1.5+1
  # saves settings
  shared_preferences: ^2.5.3
  # Material You / dynamic color
  dynamic_color: ^1.8.1
  # for 'About' section in settings
  package_info_plus: ^9.0.0
  device_info_plus: ^12.1.0
  # slick animations
  flutter_animate: ^4.5.2
  # self explanatory
  file_picker: ^10.3.2
  # for toast notifs
  toastification: ^3.0.3
  # for REST API
  http: ^1.5.0
  # gets common paths
  path_provider: ^2.1.5
  # generates uuids
  uuid: ^4.5.1
  # syntax highlighting
  highlight: ^0.7.0
  # self explanatory
  permission_handler: ^12.0.1
  # basically c# path methods
  path: ^1.9.1
  # file stuff or something
  mime: ^2.0.0
  # i wonder
  logging: ^1.3.0
  # limit window sizes
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  
flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 256

dependency_overrides:
  characters: 1.4.1
  material_color_utilities: 0.13.0
  meta: 1.17.0
  test_api: 0.7.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/themes/
    - assets/models.json

  fonts:
    - family: GoogleSans # Flex
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
        # - asset: assets/fonts/GoogleSansFlex-VariableFont_wght.ttf
        # - asset: assets/fonts/GoogleSansFlex-Italic-VariableFont_wght.ttf
        #   style: italic
    - family: GoogleSansCode
      fonts:
        - asset: assets/fonts/GoogleSansCode-VariableFont_wght.ttf
        - asset: assets/fonts/GoogleSansCode-Italic-VariableFont_wght.ttf
          style: italic
