// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82v7gj0jabOTt3_a4r7urArdJVnulW24',
    appId: '1:937215531237:web:1f8b76da9c245655f15c0c',
    messagingSenderId: '937215531237',
    projectId: 'arcadia-flutter',
    authDomain: 'arcadia-flutter.firebaseapp.com',
    storageBucket: 'arcadia-flutter.firebasestorage.app',
    measurementId: 'G-WJJYSL4XWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNMO3T-fSqrP5NDrQXBKvxjO68rHS0CU',
    appId: '1:937215531237:android:f5fa3101a0ad8435f15c0c',
    messagingSenderId: '937215531237',
    projectId: 'arcadia-flutter',
    storageBucket: 'arcadia-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG_q5UJ5ZmfSoPgDuRKQSCO7aiETJcwPo',
    appId: '1:937215531237:ios:ab29b5972f5898acf15c0c',
    messagingSenderId: '937215531237',
    projectId: 'arcadia-flutter',
    storageBucket: 'arcadia-flutter.firebasestorage.app',
    iosBundleId: 'egirlmilkers.arcadia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG_q5UJ5ZmfSoPgDuRKQSCO7aiETJcwPo',
    appId: '1:937215531237:ios:ab29b5972f5898acf15c0c',
    messagingSenderId: '937215531237',
    projectId: 'arcadia-flutter',
    storageBucket: 'arcadia-flutter.firebasestorage.app',
    iosBundleId: 'egirlmilkers.arcadia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD82v7gj0jabOTt3_a4r7urArdJVnulW24',
    appId: '1:937215531237:web:077e109ac1d9f171f15c0c',
    messagingSenderId: '937215531237',
    projectId: 'arcadia-flutter',
    authDomain: 'arcadia-flutter.firebaseapp.com',
    storageBucket: 'arcadia-flutter.firebasestorage.app',
    measurementId: 'G-BC8TX36JQ1',
  );
}
